### ISSUE TITLE
Command to allow for easy gang unenlistment 

### ISSUE THREAD

**Issue by Camology** [theGordHoard/hoardbot#10]
Would appreciate a command to allow for easy gang removal, something like 

%gangs @ role --cleanup 

which would remove the @ role from everyone who has it on the server, but not delete the role since I usually reuse them for times sake.

**Comment by katlyn** [comment]
0fac514 closes this issue. Using the `%gangs disband` command will remove gang roles from all members.

**Comment by Camology** [comment]
@theGordHoard  can you add this to the %help message or do some sort of --help sub menu in the %gangs command

**Comment by Camology** [comment]
disregard, it shows up in help %gangs
